### ISSUE TITLE
Ranking by doc or paragraph?

### ISSUE THREAD

**Issue by erdnaxel** [bnosac/textrank#10]
Hello:

the package works great!

I'm trying to rank tweets and I would like to rank them as documents, not as sentences, so that all the content of a tweet is used in the ranking, instead of having the separate sentences ranked individually.

Is there a way to do that? It feels like I should be able to use "doc_id" to do that, but I can't find a way to do it.

**Comment by jwijffels** [comment]
Make sure the first column of the data argument and the terminology argument of function textrank_sentences is a tweet id which should be a integer.
