### ISSUE TITLE
textrank_sentences to filter out dataframes of one sentence

### ISSUE THREAD

**Issue by Anjs04** [bnosac/textrank#3]
textrank_sentences() should contain stopif(dim(sentences)[1] == 1) to cover the case in which textrank_sentences if fed a piece of text that tokenises to only one sentence.

**Comment by jwijffels** [comment]
What is the point in applying `textrank_sentences` if you only have one sentence?

**Comment by Anjs04** [comment]
Applying textrank_sentences to multiple pieces of text with an unknown amount of sentences. It causes a memory leak instead of just returning an error.

**Comment by jwijffels** [comment]
I've added your suggested stop condition in the function.
