### ISSUE TITLE
[Clarification] textrank_sentences()

### ISSUE THREAD

**Issue by fahadshery** [bnosac/textrank#5]
Hi,

I need some clarification on `stopifnot(sum(duplicated(data[, 1])) == 0)` when using `textrank_sentences()`
I dedup my sentences and my terminology as well using `sentences <- unique(verbatim_tokens[, c("sentence_id", "sentence")])
terminology <- subset(verbatim_tokens, upos %in% c("NOUN", "ADJ"))
terminology <- terminology[, c("sentence_id", "lemma")]
terminology <- unique(terminology[, c("sentence_id", "lemma")])`

But I still get this error `Error in textrank_sentences(data = sentences, terminology = terminology) : sum(duplicated(data[, 1])) == 0 is not TRUE`
I did debugonce(textrank_sentences) and `data[,1]` seems to be my `sentence_id` which is bound to be duplicated?

**Comment by jwijffels** [comment]
Same issue as 
https://github.com/bnosac/textrank/issues/1
Solution was geven there

**Comment by fahadshery** [comment]
perfect. thanks it worked out well.

Could we also bring in other Algorithms such as this [python library](https://medium.com/@ondenyi.eric/extractive-text-summarization-techniques-with-sumy-3d3b127a0a32)?

Cheers,

**Comment by jwijffels** [comment]
Lexrank and latent semantic analysis are 2 other packages which are on cran since a long time already.
Don't know about Luhn.

**Comment by jwijffels** [comment]
Any other algorithms you had in mind?
